[package]
name = "note-system"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7", features = ["desktop"] }
jiff = "0.2"
typst-syntax = "0.15"

[lints.rust]
non_upper_case_globals = "allow"
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage_nightly)"] }

[lints.clippy]
manual_range_contains = "allow"
